### ISSUE TITLE
Add hability to vote for any member 

### ISSUE THREAD

**Issue by rafaelChelo** [chelofinance/talent_client#2]
For any newcomers into the talent dao team the members that are already in the DAO should be able to vote for them

**Comment by rafaelChelo** [comment]
@Ophircohenn  
For any voting process the talent dao team can choose many members, right? How is the voting process for these members? 

a - approved members must have x% of approves and y% of quorum?
b - approved members are the x with best rates of approval? Example: let's say that there are 10 applicants, and the process stipulates that the 3 best performers will be choosen.

**Comment by Ophircohenn** [comment]
let me ask them to be sure. 
any alumni member can vote 3 times per event. 
any sponsers/team can vote for 5 I think but let me check. 
a candidate can't vote because he doesn't have the governance NFT

I would like that the top 10 members will win for any event but let this number be adjustive by the talent house.

**Comment by rafaelChelo** [comment]
@Ophircohenn  Ok! Those changes are more related to the contracts. It won't be hard to implement

- I'll leave "variable" the 3 times vote for alumni members, it will depend on the talent owner wallet to change this
- I'll leave the 5 times also variable
- Also the top 10 members. 
- To differentiate between events, votes will be pooled together with an ID (the event)

Also, to clarify. Since we are going to use Elastic supply for the voting, the token won't be an NFT, it will be a token, because an nft cant have elastic supply. Is this a problem?
