### ISSUE TITLE
Interface for adding new events - Questions

### ISSUE THREAD

**Issue by rafaelChelo** [chelofinance/talent_client#3]
For a given new event where the talent team will add more members, we need an interface to create the event and upload information about it.

Currently we dont have a design for this and I have the following questions:

In the talent dao application process I see that they can have many processes. In our design these processes are differenciated and many can have different applicants. 

Talent dao team should be able to create application processes in our application?
If yes we need a design for it with the fields that will need to be filled about the process
If not then we should remove the interfaces with the "events" in the figma and only focus on the addition and voting for members.

**Comment by rafaelChelo** [comment]
@Ophircohenn when you're available, please help me answer those questions above

**Comment by Ophircohenn** [comment]
Yes I think it is smarter that we will create a UXUI for them to add an event so they won't be depended on us for any event (less effort for long term). I will ask the kid to create a design for it.

**Comment by Ophircohenn** [comment]
I am not sure that I understood what you wrote about the processes
