### ISSUE TITLE
Interface for the voting process - Questions

### ISSUE THREAD

**Issue by rafaelChelo** [chelofinance/talent_client#4]
Given a newcomer that has not been added to the mini DAO. I think there should be a better way to see the voting status.

Currently in our figma, the only things we can know about a given proposal/newcomer is how many voters have voted "yes" for him. We cant see how many should vote yes to accept him/her (quorum), we cant see if anyone has voted against adding him.
We cant also see how many shares/voting power will be given to this new member (unless his voting power is just 1 vote).

@Ophircohenn tell me what do you think about adding another view for all this information. We could do it on the "member" section, where talent members can see the questions/answers from the newcomer

**Comment by Ophircohenn** [comment]
That sounds like a great Idea, lets write it to the kid. 
A vote of team/sponsors should have more value as we discuss before.
